disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Fable Spagat"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Fable Spagat"
  email = "hspagat246@gmail.com"
#   image = "images/profilepic.png"
#   imageQuality = 96
#   headline = "Game design and programming \n with a particular passion for UI, tools programming, and economy"
#   bio = "I expect to graduate with a BS in Game Design with a minor in Game Programming"
  links = [
#     { email = "mailto:hspagat246@gmail.com" },
#     { discord = "https://discord.gg/invitecode" },
    { github = "https://github.com/fablespagat" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
    { itch-io = "https://finding-nobody.itch.io/" },
    { linkedin = "https://www.linkedin.com/in/fable-spagat/" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { youtube = "https://youtube.com/username" },
  ]
